name: Release Build
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g. v1.0.0)'
        required: true
        default: 'v0.0.0'

permissions:
  contents: write # Required for creating releases
  actions: write

env:
  VERSION: ${{ github.event_name == 'push' && github.ref_name || github.event.inputs.version }}
  CGO_ENABLED: 1
  LDFLAGS: "-s -w" # Strip debug info and DWARF tables

jobs:
  build:
    strategy:
      matrix:
        target:
          - os: windows
            arch: amd64
            ext: '.exe'
            runner: windows-latest
            shell: powershell
            name: 'windows-amd64'
          - os: linux
            arch: amd64
            ext: ''
            runner: ubuntu-latest
            shell: bash
            name: 'linux-amd64'

    runs-on: ${{ matrix.target.runner }}
    steps:
    - uses: actions/checkout@v4

    - name: Debug Environment
      run: |
        echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
        echo "Current directory: $(pwd)"
        echo "Directory contents:"
        ls -la
        echo "Looking for cmd directory:"
        find . -name "cmd" -type d
        echo "Looking for main.go:"
        find . -name "main.go" -type f
      shell: bash

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.4'

    - name: Install dependencies
      run: |
        go get github.com/mattn/go-sqlite3@v1.14.24
        go get github.com/mmcdole/gofeed@v1.3.0
        go get golang.org/x/crypto@v0.28.0
        go get golang.org/x/net@v0.30.0

    - name: Create Directories and Install UPX (Linux) 
      if: runner.os == 'Linux'
      run: |
        mkdir -p data
        mkdir -p web/static/favicons
        mkdir -p web/static/images
        sudo apt-get update && sudo apt-get install -y upx-ucl
      shell: bash

    - name: Create Directories (Windows)
      if: runner.os == 'Windows'
      run: |
        New-Item -ItemType Directory -Force -Path data
        New-Item -ItemType Directory -Force -Path web\static\favicons
        New-Item -ItemType Directory -Force -Path web\static\images
      shell: powershell

    - name: Setup MSYS2 (Windows)
      if: runner.os == 'Windows'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-pkg-config

    - name: Build (Linux)
      if: runner.os == 'Linux'
      env:
        GOOS: ${{ matrix.target.os }}
        GOARCH: ${{ matrix.target.arch }}
        BINARY_NAME: "infoscope_${{ matrix.target.name }}_${{ env.VERSION }}${{ matrix.target.ext }}"
        CGO_ENABLED: 1
      run: |
        go build -v -trimpath -ldflags="${LDFLAGS} -X main.Version=${{ env.VERSION }}" -o "${BINARY_NAME}" ./cmd/infoscope
        upx --best --lzma "${BINARY_NAME}"

    - name: Build (Windows) 
      if: runner.os == 'Windows'
      env:
        GOOS: ${{ matrix.target.os }}
        GOARCH: ${{ matrix.target.arch }}
        BINARY_NAME: "infoscope_${{ matrix.target.name }}_${{ env.VERSION }}${{ matrix.target.ext }}"
        CGO_ENABLED: 1
      shell: powershell
      run: |
        $env:PATH = "C:\msys64\mingw64\bin;C:\msys64\usr\bin;$env:PATH"
        gcc --version
        $env:CC = "gcc"
        go build -v -trimpath -ldflags="${env:LDFLAGS} -X main.Version=${{ env.VERSION }}" -o "${env:BINARY_NAME}" ./cmd/infoscope

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          infoscope_*-amd64_${{ env.VERSION }}*
        name: Release ${{ env.VERSION }}
        tag_name: ${{ github.event_name == 'workflow_dispatch' && env.VERSION || github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}